version: '3'

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
#    environment:
#      - NEO4J_dbms_shell_enabled=true
#      - NEO4J_AUTH=none
    volumes:
      - ./data:/data